### ISSUE TITLE
How to use one GPU for training? 

### ISSUE THREAD

**Issue by kelisiya** [microsoft/transductive-vos.pytorch#10]

**Comment by mofang2016** [comment]
Maybe you should make sure --nproc_per_node=1. In addition, the devices can be set via CUDA_VISIBLE_DEVICES.
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 12347 --nproc_per_node=1 main.py`

**Comment by eastOffice** [comment]
See #7
