### ISSUE TITLE
No annotation_centroids.npy file

### ISSUE THREAD

**Issue by OasisYang** [microsoft/transductive-vos.pytorch#2]
Thanks for sharing your codes. I tried to train a model on DAVIS2017 dataset, but I found there's no file named "annotation_centroids.npy", which should be loaded here. Do you plan to share this file and what's the meaning of it?
https://github.com/microsoft/transductive-vos.pytorch/blob/103ff58011b195bab18482d3d8e3572c7c1c2c94/main.py#L137

**Comment by eastOffice** [comment]
Sorry I missed it and thanks for pointing out. It contains the RGB values of annotaions' colors and is used to assign labels.
