### ISSUE TITLE
the problems of pretrainedmodel

### ISSUE THREAD

**Issue by pixelsmaker** [microsoft/transductive-vos.pytorch#4]
I've downloaded the davis_train.tar and youtube_train.tar, but I can't successful unzip the tar package, it seems that some data is corrupted, I don't know where the problems come from...

**Comment by pixelsmaker** [comment]
And I've only got 2 GPUs with 11 GB CUDA memory each, how can I change the parameters to train the model on DAVIS?

**Comment by eastOffice** [comment]
Hello,

1. the .tar file is the model that can be directly loaded by torch.load(), which doesn't need to be untared.
2. You can try a smaller batchsize first, the rest of the training parameters may not be optimal for a smaller batchsize, but shouldn't be very different from the default ones.
