### ISSUE TITLE
Inference without the motion prior

### ISSUE THREAD

**Issue by juntingzh** [microsoft/transductive-vos.pytorch#9]
Thanks for sharing such a neat implementation 

When I try to understand the effect of the motion prior, I ran inference without the motion prior by commenting off the following lines:
https://github.com/microsoft/transductive-vos.pytorch/blob/5146b32c953c3fe90ed3caee67c02ed20dfa8c7e/lib/predict.py#L48-L55

However, the final score was not the same as what was reported in the paper (J=69.0 in Table 2). Here is what I got:
+--------------+--------+----------+---------+--------+----------+---------+
|    Method    | J_mean | J_recall | J_decay | F_mean | F_recall | F_decay |
+--------------+--------+----------+---------+--------+----------+---------+
| val-no-motion | 0.618  |  0.714   |  0.224  | 0.675  |  0.772   |  0.253  |
+--------------+--------+----------+---------+--------+----------+---------+

Could you please help me understand what went wrong? What was the setting for the ablation study in the paper? Thank you!

**Comment by eastOffice** [comment]
Hello,

The motion prior corresponds to line 48 - 53, where different sigmas are applied to compute different weights. In your case, no weights are applied and a worse result is expected.
